spring.application.name=ai-lead-analyzer


# Application metadata
internal.email=cvannor63@gmail.com
business.name=Curtis Vannor


# Database configuration
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true


# Basic configuration required for auto-discovery
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Secret keys and credentials (to be set as environment variables in production)
openai.api.key=${OPENAI_API_KEY}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.username=${SPRING_MAIL_USERNAME}
