spring.application.name=ai-lead-analyzer
internal.email=cvannor63@gmail.com

# Basic configuration required for auto-discovery
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

openai.api.key=${OPENAI_API_KEY}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.username=${SPRING_MAIL_USERNAME}

business.name=Curtis Vannor
